# Generated by Django 3.2.4 on 2021-06-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=200)),
                ('profissional', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=300)),
                ('sujeitos', models.CharField(max_length=350)),
                ('avaliacao', models.CharField(max_length=400)),
            ],
        ),
    ]
