# Generated by Django 3.2.4 on 2021-06-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('turno', models.CharField(max_length=30, verbose_name='Turno')),
                ('profissional', models.CharField(max_length=100, verbose_name='Profissional')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('acao', models.CharField(max_length=100, verbose_name='Ação')),
                ('demanda', models.CharField(max_length=100, verbose_name='Demanda')),
                ('encaminhamento', models.CharField(max_length=100, verbose_name='Encaminhamento')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
