# Generated by Django 3.2.4 on 2021-06-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('aniversario', models.DateField(verbose_name='Data de Nascimento')),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('escolaridade', models.CharField(max_length=100, verbose_name='Escolaridade')),
                ('genero', models.CharField(max_length=30, verbose_name='Genero')),
                ('etnia', models.CharField(max_length=50, verbose_name='Etnia')),
                ('natural', models.CharField(max_length=100, verbose_name='Natural')),
                ('spa', models.CharField(max_length=100, verbose_name='SPA')),
                ('beneficios', models.CharField(max_length=100, verbose_name='Beneficios')),
                ('temporua', models.CharField(max_length=25, verbose_name='Tempo na Rua')),
                ('datacadastro', models.DateField(verbose_name='Data do Cadastro')),
                ('profissional', models.CharField(max_length=100, verbose_name='Profissional')),
            ],
        ),
    ]
